### ISSUE TITLE
berks-api bails on start - NoMethodError: `new_link' for nil:NilClass

### ISSUE THREAD

**Issue by kplimack** [berkshelf/berkshelf-api#169]
Gist -> (https://gist.github.com/kplimack/762a32f80bb863b8e05d)
````
root@default-debian-74:/root# /opt/berkshelf/vendor/bin/berks-api  -p 26200 -c /etc/berkshelf/config.json --debug -V
I, [2014-12-04T22:52:14.037399 #19661]  INFO -- : Cache manager starting...
I, [2014-12-04T22:52:14.038384 #19661]  INFO -- : Loading save from /etc/berkshelf/.berkshelf/api-server/cerch
W, [2014-12-04T22:52:14.235579 #19661]  WARN -- : Endpoints in config have changed - invalidating cache
I, [2014-12-04T22:52:14.236950 #19661]  INFO -- : Cache contains 0 items
I, [2014-12-04T22:52:14.243111 #19661]  INFO -- : Cache Builder starting...
E, [2014-12-04T22:52:14.244009 #19661] ERROR -- : Actor crashed!
NoMethodError: undefined method `new_link' for nil:NilClass
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/supervision_group.rb:141:in `start'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/supervision_group.rb:129:in `initialize'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/supervision_group.rb:85:in `new'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/supervision_group.rb:85:in `add'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/supervision_group.rb:72:in `supervise'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
	/opt/ruby-210/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
E, [2014-12-04T22:52:14.244087 #19661] ERROR -- : Actor crashed
````

I'm able to start the berks api without a config file specified.... but not with one

@Eulipion on IRC #Chef

**Comment by milligana** [comment]
I discovered this too.  It turns out to be a syntax error in your config.json ....
