### ISSUE TITLE
Ugly crash is build_interval is string

### ISSUE THREAD

**Issue by joerg** [berkshelf/berkshelf-api#184]
If the build_interval is set to a string in the chef attributes an ugly ugly crash happens in the app.
```node.set['berkshelf_api']['config']['build_interval'] = '5.0' # Notice the string here```

```
I, [2015-04-28T08:32:23.767693 #10562]  INFO -- : About to merge cookbooks
I, [2015-04-28T08:32:23.767772 #10562]  INFO -- : Cache manager adding (105) items...
I, [2015-04-28T08:32:23.772801 #10562]  INFO -- : Cache manager removing (0) items...
I, [2015-04-28T08:32:23.772900 #10562]  INFO -- : Cache manager cache updated.
I, [2015-04-28T08:32:23.772931 #10562]  INFO -- : Cache manager cache updated.
E, [2015-04-28T08:32:23.773548 #10562] ERROR -- : Actor crashed!
TypeError: String can't be coerced into Float
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/timers-4.0.1/lib/timers/timer.rb:81:in `+'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/timers-4.0.1/lib/timers/timer.rb:81:in `reset'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/timers-4.0.1/lib/timers/timer.rb:23:in `initialize'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/timers-4.0.1/lib/timers/group.rb:38:in `new'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/timers-4.0.1/lib/timers/group.rb:38:in `after'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:264:in `before_suspend'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid.rb:113:in `suspend'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:275:in `sleep'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid.rb:398:in `sleep'
	/opt/berkshelf-api/v2.1.1/lib/berkshelf/api/cache_builder.rb:40:in `block in build_loop'
	/opt/berkshelf-api/v2.1.1/lib/berkshelf/api/cache_builder.rb:37:in `loop'
	/opt/berkshelf-api/v2.1.1/lib/berkshelf/api/cache_builder.rb:37:in `build_loop'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/opt/berkshelf-api/v2.1.1/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
I, [2015-04-28T08:32:23.773723 #10562]  INFO -- : Cache Builder shutting down...
W, [2015-04-28T08:32:23.775447 #10562]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
```

I know this is hardly a bug, it took me a while to find out what was going on.

**Comment by mjuszczak** [comment]
@reset I believe this bug is related to this:

https://github.com/berkshelf/berkshelf-api/issues/108

**Comment by lamont-granquist** [comment]
would take a PR, but closing for now
