### ISSUE TITLE
Cannot deploy berkshelf-api-server cookbook on Oracle Linux

### ISSUE THREAD

**Issue by aminrasooli** [berkshelf/berkshelf-api#185]
Hello,

I would like to deploy the cookbook 'berkshelf-api-server', '~> 2.1.1' On the Oracle Linux instance of EC2.
I depend on 'berkshelf-api-server' cookbook and include that in my recipe. I keep receiving this error. Please direct me.

```
[0m2015-05-24T19:05:42-07:00 INFO: Running queued delayed notifications before re-raising exception
[0m
Running handlers:[0m
2015-05-24T19:05:42-07:00 ERROR: Running exception handlers
Running handlers complete
[0m2015-05-24T19:05:42-07:00 ERROR: Exception handlers complete
2015-05-24T19:05:42-07:00 FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 7 resources updated in 67.258860261 seconds[0m
2015-05-24T19:05:42-07:00 ERROR: packagecloud_repoimeyer/runit/ (runit::default line 42) had an error: RuntimeError: #<Net::HTTPNotFound 404 Not Found readbody=true>
2015-05-24T19:05:42-07:00 FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
2015-05-24T21:05:42-05:00 INFO: Completed chef-client -l info on root@55.78.110.xxx: exit status 1


In addition, /var/chef/cache/chef-stacktrace.out Contains:

anaconda-ks.cfg install.log install.log.syslog scripts
root@ip-10-15-29-xx ~# nano /var/chef/cache/chef-stacktrace.out
GNU nano 2.0.9 File: /var/chef/cache/chef-stacktrace.out

/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>' 
```

**Comment by lamont-granquist** [comment]
not really enough information to determine the problem in this ticket, might be addressed by general cookbook modernization going on in #218
