### ISSUE TITLE
invalid argument options chef server endpoint

### ISSUE THREAD

**Issue by warroyo** [berkshelf/berkshelf-api#190]
I am recieveing the following error when setting up the berkshelf-api to work with my chef server.

````
I, [2015-08-11T18:24:35.077197 #17586]  INFO -- : Cache manager starting...
I, [2015-08-11T18:24:35.077424 #17586]  INFO -- : Loading save from /root/.berkshelf/api-server/cerch
W, [2015-08-11T18:24:35.077682 #17586]  WARN -- : Endpoints in config have changed - invalidating cache
I, [2015-08-11T18:24:35.077770 #17586]  INFO -- : Cache contains 0 items
I, [2015-08-11T18:24:35.078648 #17586]  INFO -- : Cache Builder starting...
E, [2015-08-11T18:24:35.080952 #17586] ERROR -- : Actor crashed!
ArgumentError: Missing value for required option(s): ''server_url', 'client_name', 'client_key''
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/client.rb:57:in `validate_options'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.2.0/lib/ridley/client.rb:124:in `initialize'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
E, [2015-08-11T18:24:35.081220 #17586] ERROR -- : Actor crashed!
````

here is my config.json

````
{
  "endpoints": [
    {
      "type": "chef_server",
      "options": {
        "url": "https://myserver.com/organizations/myorg",
        "client_name": "berkshelf",
        "client_key": "/etc/berkshelf/api-server/client.pem"
      }
    }
  ]
}
````

**Comment by warroyo** [comment]
I believe I found at what is causing the issue. on rhel6.5 `gem install berkshelf-api ` installs `celluiod 0.16.1` in noticed on ubuntu it was installing `0.16.0` I manually removed 0.16.1 and installed 0.16.0 and now it is working
