### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by thoughtarray** [berkshelf/berkshelf-api#193]
I'm having significant trouble installing this using 2 of the 3 ways mentioned.  I just can't get the `chef-solo` to work.  What's bothering me is the `gem install` method isn't working.

I've tried on Ubuntu using Vagrant and on AWS EC2.  The error that I am getting is:
```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: berkshelf-api requires celluloid (~> 0.16.0.pre); reel requires celluloid (>= 0.15.1); ridley requires celluloid (~> 0.16.0); celluloid-io requires celluloid (>= 0.17.0.pre12)
```
Any thoughts?  I feel like I am doing something painstakingly and obviously wrong since there is little on the issue that I have found via Google other than issue #186.

**Comment by quinh** [comment]
I get the same error. 
* `debian wheezy 7.8` 
* `ruby 1.9.3`

**Comment by CVTJNII** [comment]
Also seeing this on Ubuntu-14.04:

```
# gem install berkshelf-api
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: berkshelf-api requires celluloid (~> 0.16.0.pre); reel requires celluloid (>= 0.15.1); ridley requires celluloid (~> 0.16.0); celluloid-io requires celluloid (>= 0.17.0.pre12)
```

  This is blocking installs via chef-solo as the metadata.rb file uses Berkshelf::API::VERSION to set the version attribute.

```
[2015-08-27T16:04:00+00:00] DEBUG: Re-raising exception: LoadError - cannot load such file -- berkshelf/api/version
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  /chef/cookbooks/berkshelf-api/metadata.rb:3:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:153:in `apply_ruby_metadata'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:96:in `block in metadata'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:93:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:93:in `metadata'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:86:in `block in cookbook_version'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:74:in `tap'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook/cookbook_version_loader.rb:74:in `cookbook_version'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:95:in `load_cookbook'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:69:in `block (2 levels) in load_cookbooks'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:68:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:68:in `block in load_cookbooks'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:67:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_loader.rb:67:in `load_cookbooks'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/policy_builder/expand_node_object.rb:63:in `setup_run_context'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:252:in `setup_run_context'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:413:in `do_run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:200:in `block in run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:194:in `fork'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:194:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application.rb:215:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/solo.rb:221:in `block in run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/solo.rb:213:in `loop'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/solo.rb:213:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application.rb:66:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/bin/chef-solo:25:in `<top (required)>'
  /opt/chef/bin/chef-solo:23:in `load'
  /opt/chef/bin/chef-solo:23:in `<main>'
```

I did find that the gem install will succeed if 'bundle install' is run from the repo first:

```
/tmp/berkshelf-api# bundle install
Fetching git://github.com/reset/berkflow.git
Cloning into bare repository '/var/lib/gems/1.9.1/cache/bundler/git/berkflow-adec2a3694aa43d741e59fc5318230d27c308365'...
remote: Counting objects: 311, done.
remote: Total 311 (delta 0), reused 0 (delta 0), pack-reused 311
Receiving objects: 100% (311/311), 44.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (129/129), done.
Checking connectivity... done.
Cloning into '/var/lib/gems/1.9.1/bundler/gems/berkflow-afcb4afb8340'...
done.
Fetching git://github.com/berkshelf/berkshelf.git
Cloning into bare repository '/var/lib/gems/1.9.1/cache/bundler/git/berkshelf-0826e7a47558e0652f13ee63c46ed0cd562e0afb'...
remote: Counting objects: 20915, done.
remote: Total 20915 (delta 0), reused 0 (delta 0), pack-reused 20915
Receiving objects: 100% (20915/20915), 6.16 MiB | 924.00 KiB/s, done.
Resolving deltas: 100% (9915/9915), done.
Checking connectivity... done.
Cloning into '/var/lib/gems/1.9.1/bundler/gems/berkshelf-2ae2f7c42b1c'...
done.
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Installing i18n (0.7.0)
Installing json (1.8.2)
Installing minitest (5.5.1)
Installing thread_safe (0.3.4)
Installing tzinfo (1.2.2)
Installing activesupport (4.2.0)
Installing addressable (2.3.6)
Installing builder (3.2.2)
Installing gyoku (1.2.2)
Installing mini_portile (0.6.2)
Installing nokogiri (1.6.5)
Installing akami (1.2.2)
Installing ffi (1.9.6)
Installing archive (0.0.6)
Installing descendants_tracker (0.0.4)
Installing ice_nine (0.11.1)
Installing axiom-types (0.1.1)
Installing multipart-post (2.0.0)
Installing faraday (0.9.1)
Installing berkshelf-api-client (1.2.1)
Installing buff-extensions (1.0.0)
Installing hashie (2.1.2)
Installing varia_model (0.4.0)
Installing buff-config (1.0.1)
Installing buff-ruby_engine (0.1.0)
Installing buff-shell_out (0.2.0)
Installing hitimes (1.2.2)
Installing timers (4.0.1)
Installing celluloid (0.16.0)
Installing nio4r (1.1.0)
Installing celluloid-io (0.16.1)
Installing cleanroom (1.0.0)
Installing minitar (0.5.4)
Installing sawyer (0.6.0)
Installing octokit (3.7.0)
Installing retryable (2.0.0)
Installing buff-ignore (1.1.1)
Installing erubis (2.7.0)
Installing mixlib-log (1.6.0)
Installing mixlib-authentication (1.3.0)
Installing net-http-persistent (2.9.4)
Installing semverse (1.2.1)
Installing ridley (4.1.2)
Installing dep-selector-libgecode (1.0.2)
Installing dep_selector (1.0.3)
Installing solve (1.2.1)
Installing thor (0.19.1)
Using berkshelf (3.2.2) from git://github.com/berkshelf/berkshelf.git (at master)
Installing net-ssh (2.9.2)
Installing net-ssh-gateway (1.2.0)
Installing gssapi (1.0.3)
Installing httpclient (2.6.0.1)
Installing little-plugger (1.1.3)
Installing multi_json (1.10.1)
Installing logging (1.8.2)
Installing rubyntlm (0.1.1)
Installing rack (1.6.0)
Installing httpi (0.9.7)
Installing nori (1.1.5)
Installing wasabi (1.0.0)
Installing savon (0.9.5)
Installing uuidtools (2.1.5)
Installing winrm (1.1.3)
Installing ridley-connectors (2.3.1)
Using berkflow (0.6.2) from git://github.com/reset/berkflow.git (at master)
Installing multi_xml (0.5.5)
Installing rack-accept (0.4.5)
Installing rack-mount (0.8.3)
Installing coercible (1.0.0)
Installing equalizer (0.0.9)
Installing virtus (1.0.4)
Installing grape (0.10.1)
Installing msgpack (0.5.10)
Installing grape-msgpack (0.1.2)
Installing http-form_data (1.0.1)
Installing http_parser.rb (0.6.0)
Installing http (0.8.3)
Installing websocket_parser (0.1.6)
Installing reel (0.5.0)
Using berkshelf-api (2.1.1) from source at .
Installing libyajl2 (1.2.0)
Installing ffi-yajl (1.3.1)
Installing chef-zero (3.2.1)
Installing childprocess (0.5.5)
Installing coderay (1.1.0)
Installing unicode_utils (1.4.0)
Installing coolline (0.5.0)
Installing diff-lcs (1.2.5)
Installing formatador (0.2.5)
Installing rspec-core (2.99.2)
Installing rspec-expectations (2.99.2)
Installing rspec-mocks (2.99.3)
Installing rspec (2.99.0)
Installing ruby-progressbar (1.7.1)
Installing fuubar (1.3.3)
Installing rb-fsevent (0.9.4)
Installing rb-inotify (0.9.5)
Installing rb-kqueue (0.2.3)
Installing listen (1.3.1)
Installing lumberjack (1.0.9)
Installing method_source (0.8.2)
Installing slop (3.6.0)
Installing pry (0.10.1)
Installing guard (1.8.3)
Installing guard-rspec (3.1.0)
Installing spork (0.9.2)
Installing guard-spork (1.5.2)
Installing rack-test (0.6.3)
Installing redcarpet (3.2.2)
Installing yard (0.8.7.6)
Using bundler (1.3.5)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

/tmp/berkshelf-api# gem install berkshelf-api
Fetching: berkshelf-api-2.1.1.gem (100%)
Fetching: nenv-0.2.0.gem (100%)
Fetching: dotenv-2.0.2.gem (100%)
Fetching: rspec-logsplit-0.1.3.gem (100%)
Fetching: unf_ext-0.0.7.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: unf-0.1.4.gem (100%)
Fetching: domain_name-0.5.24.gem (100%)
Fetching: http-cookie-1.0.2.gem (100%)
Successfully installed berkshelf-api-2.1.1
Successfully installed nenv-0.2.0
Successfully installed dotenv-2.0.2
Successfully installed rspec-logsplit-0.1.3
Successfully installed unf_ext-0.0.7.1
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.24
Successfully installed http-cookie-1.0.2
8 gems installed
Installing ri documentation for berkshelf-api-2.1.1...
Building YARD (yri) index for berkshelf-api-2.1.1...
Installing ri documentation for nenv-0.2.0...
Building YARD (yri) index for nenv-0.2.0...
Installing ri documentation for dotenv-2.0.2...
Building YARD (yri) index for dotenv-2.0.2...
Installing ri documentation for rspec-logsplit-0.1.3...
Building YARD (yri) index for rspec-logsplit-0.1.3...
Installing ri documentation for unf_ext-0.0.7.1...
Building YARD (yri) index for unf_ext-0.0.7.1...
Installing ri documentation for unf-0.1.4...
Building YARD (yri) index for unf-0.1.4...
Installing ri documentation for domain_name-0.5.24...
Building YARD (yri) index for domain_name-0.5.24...
Installing ri documentation for http-cookie-1.0.2...
Building YARD (yri) index for http-cookie-1.0.2...
Installing RDoc documentation for berkshelf-api-2.1.1...
Installing RDoc documentation for nenv-0.2.0...
Installing RDoc documentation for dotenv-2.0.2...
Installing RDoc documentation for rspec-logsplit-0.1.3...
Installing RDoc documentation for unf_ext-0.0.7.1...
Installing RDoc documentation for unf-0.1.4...
Installing RDoc documentation for domain_name-0.5.24...
Installing RDoc documentation for http-cookie-1.0.2...
```

However the gem doesn't run:
```
/tmp/berkshelf-api# berks-api 
/var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'archive': archive: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libarchive.so': libarchive.so: cannot open shared object file: No such file or directory
        from /var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
        from /var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
        from /var/lib/gems/1.9.1/gems/archive-0.0.6/lib/archive/libarchive.rb:136:in `<module:LibArchive>'
        from /var/lib/gems/1.9.1/gems/archive-0.0.6/lib/archive/libarchive.rb:77:in `<module:Archive>'
        from /var/lib/gems/1.9.1/gems/archive-0.0.6/lib/archive/libarchive.rb:3:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /var/lib/gems/1.9.1/gems/archive-0.0.6/lib/archive.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector/supermarket.rb:2:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector.rb:4:in `require_relative'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector.rb:4:in `<module:SiteConnector>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector.rb:3:in `<module:API>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector.rb:2:in `<module:Berkshelf>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/site_connector.rb:1:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:26:in `require_relative'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:26:in `<module:API>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:10:in `<module:Berkshelf>'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:9:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:72:in `start'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:58:in `run'
        from /var/lib/gems/1.9.1/gems/berkshelf-api-2.1.1/bin/berks-api:5:in `<top (required)>'
        from /usr/local/bin/berks-api:23:in `load'
        from /usr/local/bin/berks-api:23:in `<main>'
```

Chef-solo also continues to fail with the same error: ERROR: cannot load such file -- berkshelf/api/version

I'm attempting to sandbox the API in Docker so my environment is clean, no gems other than the ones installed for Chef 11 and bundler exist before the install commands listed above:

```
# gem list

*** LOCAL GEMS ***

bundler (1.3.5)
net-http-persistent (2.9)
rdoc (3.9.4)
thor (0.18.1.20140116)
```

**Comment by CVTJNII** [comment]
Looks like the libarchive error is https://github.com/berkshelf/berkshelf-api/issues/167

**Comment by lamont-granquist** [comment]
seems to be a dup of the depsolver problems with ruby 1.9.3 and rubygems 1.8.23
