### ISSUE TITLE
berkshelf-api doesn't trust the system SSL CA bundle after 1.2.1

### ISSUE THREAD

**Issue by travis-altiscale** [berkshelf/berkshelf-api#194]
Since version 1.2.1 we are no longer able to use berkshelf with our berks api server / chef server which is using SSL certificates generated from our internal certificate authority (which is properly installed).  It works and the certificate is valid in 1.2.1, in >= 1.3.0 it fails with an SSL error.

#### 1.2.1
```
# gem list | grep berkshelf-api
berkshelf-api-client (1.2.1)
# berks install
Resolving cookbook dependencies...
Fetching '<redacted_cookbook>' from source at .
Fetching cookbook index from https://<redacted-berks-api-server>...
Using <redacted_cookbook> (1.0.18) from source at .
Installing apt (2.7.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing bluepill (2.3.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing build-essential (2.2.3) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing centos_base (1.7.27) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing chef-client (3.5.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing chef_handler (1.1.4) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing cron (1.6.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing cve_2013_2094 (0.0.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing erlang (1.5.6) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing logrotate (1.9.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing nginx (2.7.4) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing nrpe_client (0.0.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing ohai (2.0.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing packagecloud (0.0.19) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing rabbitmq (3.2.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing redisio (1.7.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing rsyslog (2.0.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing runit (1.7.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing sensu (2.1.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing sudo (2.7.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing sysctl (0.6.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing ulimit (0.3.2) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing vcc_java (1.0.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing windows (1.37.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing yum (3.0.4) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing yum-epel (0.6.1) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
Installing yum-erlang_solutions (0.2.0) from https://<redacted-berks-api-server> ([chef_server] https://<redacted-chef-server>:443/)
```
#### 1.3.0
```
# gem list | grep berkshelf-api
berkshelf-api-client (1.3.0, 1.2.1)
# berks install
Resolving cookbook dependencies...
Fetching '<redacted_cookbook>' from source at .
Fetching cookbook index from https://<redacted-berks-api-server>...
/Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:307:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:307:in `ssl_connect'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:755:in `block in connect'
        from /Users/travis/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
        from /Users/travis/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/adapter/httpclient.rb:33:in `call'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/request/retry.rb:110:in `call'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/berkshelf-api-client-1.3.0/lib/berkshelf/api_client/connection.rb:62:in `universe'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/berkshelf-3.1.2/lib/berkshelf/source.rb:22:in `build_universe'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p645@cookbook2/gems/berkshelf-3.1.2/lib/berkshelf/installer.rb:21:in `block (2 levels) in build_universe'

```

It looks to me like berkshelf-api-client switched to using faraday in 1.3.0 and it's possible this is a faraday bug.  Anyone else seeing anything like this?

**Comment by travis-altiscale** [comment]
Posted this on the wrong project, please disregard...
