### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by quinh** [berkshelf/berkshelf-api#196]
I am not a rubyist, but i want to install and ran the berkshelf-api. I've cloned the repository and managed to install berks-api via `bundle install` (after raising the RAM to 3GB of my virtual machine) and installing `libarchive-dev` on my debian system.

**Anyway**, after starting the application via `berks-api` it failed to start:
```
I, [2015-09-15T13:36:31.191800 #7500]  INFO -- : Cache manager starting...
I, [2015-09-15T13:36:31.193895 #7500]  INFO -- : Cache Builder starting...
E, [2015-09-15T13:36:31.538881 #7500] ERROR -- : Actor crashed!
Celluloid::FiberStackError: stack level too deep (please see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:27:in `rescue in deliver'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/responses.rb:11:in `dispatch'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:40:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
        /var/lib/gems/1.9.1/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
        /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
I, [2015-09-15T13:36:31.539330 #7500]  INFO -- : Cache Manager shutting down...
I, [2015-09-15T13:36:31.539429 #7500]  INFO -- : Cache Builder shutting down...
/usr/local/bin/berks-api:23: stack level too deep (SystemStackError)
```

I haven't configured any json configuration file so far (in case that matters).

**Comment by kenhen93** [comment]
What version of ruby are you running. I got around this error by installing ruby 2.0.0

**Comment by quinh** [comment]
Thanks for the suggestion, i will try upgrading from 1.9.3
