### ISSUE TITLE
Doesn't play nice with ChefDK 0.11.0

### ISSUE THREAD

**Issue by scalp42** [berkshelf/berkshelf-api#205]
There's a gem conflict issue with the latest ChefDK `0.11.0`:

```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate sawyer-0.6.0, because addressable-2.4.0 conflicts with addressable (~> 2.3.5) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1408:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `each'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1410:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder/worker/github.rb:1:in `<top (required)>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder/worker.rb:87:in `require_relative'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder/worker.rb:87:in `block in <top (required)>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder/worker.rb:86:in `each'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder/worker.rb:86:in `<top (required)>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder.rb:3:in `require_relative'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder.rb:3:in `<class:CacheBuilder>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder.rb:2:in `<module:API>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/cache_builder.rb:1:in `<top (required)>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:19:in `require_relative'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:19:in `<module:API>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:10:in `<module:Berkshelf>'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api.rb:9:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:72:in `start'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:58:in `run'
	from /root/.chefdk/gem/ruby/2.1.0/gems/berkshelf-api-2.1.1/bin/berks-api:5:in `<top (required)>'
	from /root/.chefdk/gem/ruby/2.1.0/bin/berks-api:22:in `load'
	from /root/.chefdk/gem/ruby/2.1.0/bin/berks-api:22:in `<main>'
```

`0.10.0` is fine though.

**Comment by scalp42** [comment]
Trying with 0.11.2.

**Comment by scalp42** [comment]
Looks like 0.11.2 is fine.
