### ISSUE TITLE
NameError: uninitialized constant HTTP::Response::STATUS_CODES

### ISSUE THREAD

**Issue by scalp42** [berkshelf/berkshelf-api#206]
Running into this error:

```
/opt/berkshelf-api # berks-api -c config.json
I, [2016-02-19T23:17:05.924428 #617]  INFO -- : Cache manager starting...
I, [2016-02-19T23:17:05.925765 #617]  INFO -- : Cache Builder starting...
I, [2016-02-19T23:17:06.085136 #617]  INFO -- : Cache Manager shutting down...
W, [2016-02-19T23:17:06.085849 #617]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2016-02-19T23:17:06.086274 #617]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
E, [2016-02-19T23:17:06.086681 #617] ERROR -- : Actor crashed!
NameError: uninitialized constant HTTP::Response::STATUS_CODES
	/usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:10:in `<class:Response>'
	/usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:4:in `<module:Reel>'
	/usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:3:in `<top (required)>'
	/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel.rb:12:in `<top (required)>'
	/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/rest_gateway.rb:1:in `<top (required)>'
	/usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:19:in `require_relative'
	/usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:19:in `initialize'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
W, [2016-02-19T23:17:06.087631 #617]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
I, [2016-02-19T23:17:06.088084 #617]  INFO -- : Cache Builder shutting down...
/usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:10:in `<class:Response>': uninitialized constant HTTP::Response::STATUS_CODES (NameError)
	from /usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:4:in `<module:Reel>'
	from /usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel/response.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/reel-0.5.0/lib/reel.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/rest_gateway.rb:1:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:19:in `require_relative'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:19:in `initialize'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	from /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.rb:169:in `new'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:143:in `run!'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:119:in `block in run'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:118:in `loop'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/application.rb:118:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:73:in `start'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/lib/berkshelf/api/srv_ctl.rb:58:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.1/bin/berks-api:5:in `<top (required)>'
	from /usr/bin/berks-api:23:in `load'
	from /usr/bin/berks-api:23:in `<main>'
```

Gem list:

```
*** LOCAL GEMS ***

activesupport (4.2.5.1)
addressable (2.3.8)
archive (0.0.6)
axiom-types (0.1.1)
berkshelf-api (2.1.1)
bigdecimal (1.2.7)
buff-config (1.0.1)
buff-extensions (1.0.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
celluloid (0.16.0)
celluloid-io (0.16.2)
coercible (1.0.0)
descendants_tracker (0.0.4)
diff-lcs (1.2.5)
domain_name (0.5.20160128)
equalizer (0.0.11)
erubis (2.7.0)
faraday (0.9.2)
ffi (1.9.10)
grape (0.14.0)
grape-msgpack (0.1.2)
hashie (2.1.2)
hitimes (1.2.3)
http (1.0.2)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
i18n (0.7.0)
ice_nine (0.11.2)
json (1.8.3)
minitest (5.4.3)
mixlib-authentication (1.4.0)
mixlib-log (1.6.0)
msgpack (0.5.12)
multi_json (1.11.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
net-http-persistent (2.9.4)
nio4r (1.2.1)
octokit (3.8.0)
power_assert (0.2.2)
psych (2.0.8)
rack (1.6.4)
rack-accept (0.4.5)
rack-mount (0.8.3)
reel (0.5.0)
retryable (2.0.3)
ridley (4.0.0)
rspec-core (3.4.3)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
sawyer (0.6.0)
semverse (1.2.1)
test-unit (3.0.8)
thread_safe (0.3.5)
timers (4.0.4)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
varia_model (0.5.0)
virtus (1.0.5)
websocket_parser (1.0.0)
```

Only two gems installed:

```
gem install berkshelf-api bigdecimal --no-doc
```

Any pointers? Thanks in advance.

**Comment by scalp42** [comment]
Related: https://github.com/celluloid/reel/issues/213

**Comment by scalp42** [comment]
maybe @someara if you could take a look ? Looks like there's a PR to bump reel: https://github.com/berkshelf/berkshelf-api/issues/204

**Comment by someara** [comment]
investigating

**Comment by scalp42** [comment]
Working with https://github.com/scalp42/berkshelf-api/commit/640a9657924c72c0833ba9a753671b4f4e242042

**Comment by ctso** [comment]
I opened up a PR for this a while back, #204

**Comment by scalp42** [comment]
Yeah closing :smile:
