### ISSUE TITLE
uninitialized constant Grape::Formatter::Base (NameError)

### ISSUE THREAD

**Issue by scalp42** [berkshelf/berkshelf-api#210]
Running into the following error:

```
/opt/berkshelf-api # berks-api /opt/berkshelf-api/config.json
/usr/lib/ruby/gems/2.2.0/gems/grape-msgpack-0.1.2/lib/grape/msgpack.rb:39:in `<top (required)>': uninitialized constant Grape::Formatter::Base (NameError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/grape-msgpack-0.1.2/lib/grape-msgpack.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/endpoint.rb:2:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:23:in `require_relative'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:23:in `<module:API>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:10:in `<module:Berkshelf>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/srv_ctl.rb:72:in `start'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/srv_ctl.rb:58:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/bin/berks-api:5:in `<top (required)>'
	from /usr/bin/berks-api:23:in `load'
	from /usr/bin/berks-api:23:in `<main>'
```

Gem list:

```
/opt/berkshelf-api # gem list

*** LOCAL GEMS ***

activesupport (4.2.6)
addressable (2.4.0)
archive (0.0.6)
axiom-types (0.1.1)
berkshelf-api (2.1.3)
bigdecimal (1.2.7)
buff-config (1.0.1)
buff-extensions (1.0.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
celluloid (0.16.0)
celluloid-io (0.16.2)
chef-config (12.8.1)
coercible (1.0.0)
descendants_tracker (0.0.4)
diff-lcs (1.2.5)
domain_name (0.5.20160309)
equalizer (0.0.11)
erubis (2.7.0)
faraday (0.9.2)
ffi (1.9.10)
grape (0.15.0)
grape-msgpack (0.1.2)
hashie (3.4.3)
hitimes (1.2.3)
http (1.0.3)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
httpclient (2.7.1)
i18n (0.7.0)
ice_nine (0.11.2)
io-console (0.4.3)
json (1.8.3)
minitest (5.4.3)
mixlib-authentication (1.4.0)
mixlib-config (2.2.1)
mixlib-log (1.6.0)
mixlib-shellout (2.2.6)
msgpack (0.5.12)
multi_json (1.11.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
nio4r (1.2.1)
octokit (4.3.0)
power_assert (0.2.2)
psych (2.0.8)
rack (1.6.4)
rack-accept (0.4.5)
rack-mount (0.8.3)
reel (0.6.1)
retryable (2.0.3)
ridley (4.5.0)
rspec-core (3.4.4)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
sawyer (0.7.0)
semverse (1.2.1)
test-unit (3.0.8)
thread_safe (0.3.5)
timers (4.0.4)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
varia_model (0.4.1)
virtus (1.0.5)
websocket-driver (0.6.3)
websocket-extensions (0.1.2)
```

This is in Docker, so fresh gems etc:

```
RUN gem install -N berkshelf-api bigdecimal
```

**Comment by scalp42** [comment]
I'm actually going to close here as using grape 0.14.0 fixes the issue and redirect this to grape project.
